import colorPalette from '../../../../../constants/colorPalettes';

export default {
  chartData: {
    data: [
      { day: 'Sun', index: 0, value: 18 },
      { day: 'Sun', index: 1, value: 42 },
      { day: 'Sun', index: 2, value: 80 },
      { day: 'Sun', index: 3, value: 59 },
      { day: 'Sun', index: 4, value: 31 },
      { day: 'Sun', index: 5, value: 41 },
      { day: 'Sun', index: 6, value: 45 },
      { day: 'Sun', index: 7, value: 86 },
      { day: 'Sun', index: 8, value: 98 },
      { day: 'Sun', index: 9, value: 44 },
      { day: 'Sun', index: 10, value: 31 },
      { day: 'Sun', index: 11, value: 39 },
      { day: 'Sun', index: 12, value: 72 },
      { day: 'Mon', index: 0, value: 22 },
      { day: 'Mon', index: 1, value: 87 },
      { day: 'Mon', index: 2, value: 2 },
      { day: 'Mon', index: 3, value: 60 },
      { day: 'Mon', index: 4, value: 39 },
      { day: 'Mon', index: 5, value: 92 },
      { day: 'Mon', index: 6, value: 29 },
      { day: 'Mon', index: 7, value: 0 },
      { day: 'Mon', index: 8, value: 94 },
      { day: 'Mon', index: 9, value: 72 },
      { day: 'Mon', index: 10, value: 4 },
      { day: 'Mon', index: 11, value: 0 },
      { day: 'Mon', index: 12, value: 52 },
      { day: 'Tue', index: 0, value: 12 },
      { day: 'Tue', index: 1, value: 63 },
      { day: 'Tue', index: 2, value: 99 },
      { day: 'Tue', index: 3, value: 86 },
      { day: 'Tue', index: 4, value: 38 },
      { day: 'Tue', index: 5, value: 49 },
      { day: 'Tue', index: 6, value: 74 },
      { day: 'Tue', index: 7, value: 48 },
      { day: 'Tue', index: 8, value: 17 },
      { day: 'Tue', index: 9, value: 15 },
      { day: 'Tue', index: 10, value: 38 },
      { day: 'Tue', index: 11, value: 96 },
      { day: 'Tue', index: 12, value: 84 },
      { day: 'Wed', index: 0, value: 78 },
      { day: 'Wed', index: 1, value: 31 },
      { day: 'Wed', index: 2, value: 64 },
      { day: 'Wed', index: 3, value: 86 },
      { day: 'Wed', index: 4, value: 14 },
      { day: 'Wed', index: 5, value: 31 },
      { day: 'Wed', index: 6, value: 40 },
      { day: 'Wed', index: 7, value: 37 },
      { day: 'Wed', index: 8, value: 3 },
      { day: 'Wed', index: 9, value: 59 },
      { day: 'Wed', index: 10, value: 40 },
      { day: 'Wed', index: 11, value: 39 },
      { day: 'Wed', index: 12, value: 80 },
      { day: 'Thu', index: 0, value: 3 },
      { day: 'Thu', index: 1, value: 13 },
      { day: 'Thu', index: 2, value: 7 },
      { day: 'Thu', index: 3, value: 5 },
      { day: 'Thu', index: 4, value: 50 },
      { day: 'Thu', index: 5, value: 30 },
      { day: 'Thu', index: 6, value: 25 },
      { day: 'Thu', index: 7, value: 8 },
      { day: 'Thu', index: 8, value: 61 },
      { day: 'Thu', index: 9, value: 43 },
      { day: 'Thu', index: 10, value: 19 },
      { day: 'Thu', index: 11, value: 3 },
      { day: 'Thu', index: 12, value: 59 },
      { day: 'Fri', index: 0, value: 14 },
      { day: 'Fri', index: 1, value: 68 },
      { day: 'Fri', index: 2, value: 86 },
      { day: 'Fri', index: 3, value: 58 },
      { day: 'Fri', index: 4, value: 52 },
      { day: 'Fri', index: 5, value: 43 },
      { day: 'Fri', index: 6, value: 17 },
      { day: 'Fri', index: 7, value: 56 },
      { day: 'Fri', index: 8, value: 35 },
      { day: 'Fri', index: 9, value: 4 },
      { day: 'Fri', index: 10, value: 91 },
      { day: 'Fri', index: 11, value: 66 },
      { day: 'Fri', index: 12, value: 49 },
      { day: 'Sat', index: 0, value: 77 },
      { day: 'Sat', index: 1, value: 51 },
      { day: 'Sat', index: 2, value: 100 },
      { day: 'Sat', index: 3, value: 72 },
      { day: 'Sat', index: 4, value: 94 },
      { day: 'Sat', index: 5, value: 37 },
      { day: 'Sat', index: 6, value: 81 },
      { day: 'Sat', index: 7, value: 97 },
      { day: 'Sat', index: 8, value: 30 },
      { day: 'Sat', index: 9, value: 58 },
      { day: 'Sat', index: 10, value: 64 },
      { day: 'Sat', index: 11, value: 16 },
      { day: 'Sat', index: 12, value: 87 }
    ],
    xAxis: 'index',
    yAxis: 'day',
    value: 'value'
  },
  min   : 0,
  max   : 100,
  suffix: '%'
};
